### ISSUE TITLE
use which prompt

### ISSUE THREAD

**Issue by RanchiZhao** [LaVi-Lab/CLEVA#3]
i noticed that there are a few prompt choices in each dataset, i wonder which one is the final using one? maybe i should wait for the code?

**Comment by lyy1994** [comment]
The results reported in our paper and website are the mean statistics of **all** prompts. We do not have recommendations for using which specific prompt, as our purpose is to get rid of the sensitivity to prompts.

**Comment by RanchiZhao** [comment]
thanks！
