### ISSUE TITLE
don't understand mul_as_gen

### ISSUE THREAD

**Issue by RanchiZhao** [LaVi-Lab/CLEVA#4]
what does this mean in your data?
like the difference between:
```{
        "choices": {
            "item_separator": "\n",
            "item_template": "{idx}. {item}",
            "item_index": "upper"
        },
        "input": "“{translation}”这句话可以用以下哪句古文来表达：\n",
        "answer_context": "答：（请用选项序号回答）",
        "meta": {
            "language": "zh-Hans",
            "mul_as_gen": true,
            "postprocess": ["common", "upper"]
        }
    },
```
and
```{
        "input": "{translation}\n这句话可以用以下古文来表达：",
        "meta": {
            "language": "zh-Hans",
            "mul_as_gen": false
        }
    },
```
besides,` {idx}. {item}`, the idx is like a number(1/2/3/4) or chars(A/B/C/D)?

**Comment by RanchiZhao** [comment]
maybe when mul_as_gen is false, this means now will choose ppl method? instead of gen method

**Comment by lyy1994** [comment]
> what does this mean in your data? like the difference between:
> 
> ```
>         "choices": {
>             "item_separator": "\n",
>             "item_template": "{idx}. {item}",
>             "item_index": "upper"
>         },
>         "input": "“{translation}”这句话可以用以下哪句古文来表达：\n",
>         "answer_context": "答：（请用选项序号回答）",
>         "meta": {
>             "language": "zh-Hans",
>             "mul_as_gen": true,
>             "postprocess": ["common", "upper"]
>         }
>     },
> ```
> 
> and
> 
> ```
>         "input": "{translation}\n这句话可以用以下古文来表达：",
>         "meta": {
>             "language": "zh-Hans",
>             "mul_as_gen": false
>         }
>     },
> ```
> 
> besides,` {idx}. {item}`, the idx is like a number(1/2/3/4) or chars(A/B/C/D)?

For your first question, the difference between these two prompt templates is that the former (`"mul_as_gen": true`) asks LLMs to generate the answer index (e.g., A/B/C), while the latter (`"mul_as_gen": false`) uses LLMs to score all answers separately and takes the one with the highest probability as the answer. You can refer to *Multi-choice problem format* part in Appendix F.2 of our [paper](https://arxiv.org/pdf/2308.04813.pdf).

For your second question, your guess is right. `{idx}` could be numbers (1, 2, 3, etc.) or chars (A, B, C, etc.), depending on which option is specified in `item_index` (e.g., `upper` means using capital letters A/B/C). You can check out Appendix F.3 of our [paper](https://arxiv.org/pdf/2308.04813.pdf) for the idea of our implementation.

For more information on the prompting implementation, you can take a look at our [PR](https://github.com/stanford-crfm/helm/pull/1824) in HELM (Concretely, the implementation of [prompt construction](https://github.com/stanford-crfm/helm/blob/de8964e729da5aa3a469d742e71e0ceedce55628/src/helm/benchmark/scenarios/cleva_scenario.py#L60)).

**Comment by RanchiZhao** [comment]
Got it! Thank you for the clarification. I appreciate your detailed response.
