### ISSUE TITLE
run bash failed status：404

### ISSUE THREAD

**Issue by wang-qa** [LaVi-Lab/CLEVA#8]
run`bash download_data.sh`
![img_v3_027m_42eefd5b-7a44-4513-a136-8f00d79f608g](https://github.com/LaVi-Lab/CLEVA/assets/58168764/f6c7fc4a-5a7c-475c-9464-02c317fc6bd1)

Unable to download

**Comment by Jianqiao-Zhao** [comment]
Thanks for pointing it out. The problem has been fixed. You can try again. Thank you for using our CLEVA!

**Comment by wang-qa** [comment]
It has been fixed
I suggest uploading the zip file to this repository for greater convenience
