### ISSUE TITLE
The leaderboard website is inaccessible...

### ISSUE THREAD

**Issue by zhimin-z** [LaVi-Lab/CLEVA#9]
Check http://www.lavicleva.com and find it does not respond recently:
![image](https://github.com/LaVi-Lab/CLEVA/assets/8592144/34be176e-9f25-4507-af47-e8e904190a5c)
@lyy1994 @Jianqiao-Zhao

**Comment by Jianqiao-Zhao** [comment]
Hi @zhimin-z , I am looking into this issue and will make our website back online as soon as possible. Thank you for letting us know!

**Comment by zhimin-z** [comment]
> Hi @zhimin-z , I am looking into this issue and will make our website back online as soon as possible. Thank you for letting us know!

Any update?

**Comment by zhimin-z** [comment]
> > Hi @zhimin-z , I am looking into this issue and will make our website back online as soon as possible. Thank you for letting us know!
> 
> Any update?

Any update?

**Comment by Jianqiao-Zhao** [comment]
Hi @zhimin-z , we are upgrading our online platform. Before it is reopened, you can use our offline version, which is available through Stanford HELM. You can select the evaluation tasks by modifying this [configuration file](https://github.com/stanford-crfm/helm/blob/main/src/helm/benchmark/presentation/run_entries_cleva_v1.conf).

**Comment by zhimin-z** [comment]
Closed, since it is back again :)
<img width="1435" alt="image" src="https://github.com/user-attachments/assets/f100adb9-7897-491a-9f40-5ea4fc1d1d4f">
